var slider={};slider.m={};slider.v={};slider.c={};slider.logLevel=4;slider.isIE=(navigator.appName.indexOf("Microsoft")!=-1)?true:false;slider.userAgent=navigator.userAgent.toLowerCase();if(slider.userAgent.search("iphone")>-1||slider.userAgent.search("ipad")>-1||slider.userAgent.search("android")>-1){slider.isMobile=true
}slider.helpclick=function(a){if(slider.v.puzzle){slider.v.puzzle.layoutmanager(a)}};slider.log=function(b,a){if(typeof(console)=="undefined"||console==null||!slider.logLevel){return}try{if(a=="error"){console.error("slider: "+b)}else{if(a=="warn"&&slider.logLevel>=2){console.warn("slider: "+b)}else{if(a=="info"&&slider.logLevel>=3){console.info("slider: "+b)
}else{if(slider.logLevel>=4){console.log("slider: "+b)}}}}}catch(c){}};(function(a,b){b.c.sliderSize=4;b.c.isMovelLegal=function(c,e){var d={isLegal:false};if(b.m.emptyRef.x===c&&b.m.emptyRef.y!==e){d={isLegal:true,direction:"y",displacement:b.m.emptyRef.y-e}}else{if(b.m.emptyRef.y===e&&b.m.emptyRef.x!==c){d={isLegal:true,direction:"x",displacement:b.m.emptyRef.x-c}
}}return d};b.c.swap=function(g,j,e){var h,d;h=(e<0)?e*-1:e;d={x:b.m.emptyRef.x,y:b.m.emptyRef.y};for(var f=0,c=tempx=b.m.emptyRef.x,k=tempy=b.m.emptyRef.y;f<=h;f++){b.m.state[tempx][tempy]=b.m.state[c][k];tempx=c;tempy=k;if(j==="y"){k=(e<0)?k+1:k-1}else{c=(e<0)?c+1:c-1}}b.m.emptyRef.x=g.x;b.m.emptyRef.y=g.y;
b.m.state[g.x][g.y]=b.m.emptyTile;b.v.puzzle.swapTiles(d,j,e);(b.m.state.join()===b.m.solution.join())&&alert("You won the game !!!")}})(window,slider);(function(a,b){b.m.emptyTile="tile10";b.m.tileSize=160;b.m.emptyRef={x:1,y:0};b.m.state=[["tile00","tile01","tile02","tile03"],["tile10","tile11","tile12","tile13"],["tile20","tile21","tile22","tile23"],["tile30","tile31","tile32","tile33"]];
b.m.solution=[["tile33","tile32","tile01","tile23"],["tile21","tile00","tile12","tile11"],["tile31","tile02","tile30","tile22"],["tile13","tile20","tile03","tile10"]]})(window,slider);(function(a,c){var b=function(){this.placeHolder=c.v.getEl("slider");this.sourceHolder=c.v.getEl("source_holder");this.solutionHolder=c.v.getEl("solution_holder");
var g=this.placeHolder.offsetLeft;var e=this.placeHolder.offsetTop;this.previewDrag=c.v.getEl("previewDrag");this.isDragged=false;var d=this;this.paintPuzzle=function(){d.placeHolder.innerHTML="";d.previewDrag.innerHTML="";var n=document.createDocumentFragment(),o=document.createDocumentFragment();for(var m=0;
m<c.c.sliderSize;m++){for(var l=0;l<c.c.sliderSize;l++){var q=c.v.createEl("div",{id:"box"+m+l,className:"tile "+c.m.state[m][l]+" floatleft"}),k=c.v.createEl("div",{className:"tile "+c.m.solution[m][l]+" floatleft"});c.v.addHandler(q,"click",function(i,j){return function(){c.log("isDragged="+d.isDragged,"info");
if(d.isDragged&&!c.isMobile){d.isDragged=false;return}var r=c.c.isMovelLegal(i,j);(r.isLegal===true)&&c.c.swap({x:i,y:j},r.direction,r.displacement)}}(m,l));d.makeDraggable(q,{x:m,y:l});n.appendChild(q);o.appendChild(k)}}d.placeHolder.appendChild(n);d.solutionHolder.appendChild(o)};this.swapTiles=function(q,o,k){d.previewDrag.innerHTML="";
var l=(k<0)?(k*-1):k;for(var m=0,j=q.x,r=q.y;m<=l;m++){var n=c.v.getEl("box"+j+r);n.className="tile "+c.m.state[j][r]+" floatleft";if(o==="y"){r=(k<0)?r+1:r-1}else{j=(k<0)?j+1:j-1}}};this.makeDraggable=function(o,m){var q=null,i=0,n=0,l={},k=0,j=0,s=0,r=0;new c.v.Drag(o,function(z,D,B){if(z=="dragstart"){q=c.v.createEl("div",{className:"buddy_drag_clone"});
var y=l.displacement,u=m.x,t=m.y;y=(l.displacement<0)?l.displacement*-1:l.displacement;var v=document.getElementById("box"+m.x+m.y),A=document.getElementById("box"+c.m.emptyRef.x+c.m.emptyRef.y);if(l.direction==="y"){q.style.width=(y*c.m.tileSize)+"px";k=v.offsetTop;s=k+v.offsetHeight;if(l.displacement<0){u=c.m.emptyRef.x;
t=c.m.emptyRef.y+1;r=v.offsetLeft+v.offsetWidth;j=A.offsetLeft}else{r=A.offsetLeft+A.offsetWidth;j=v.offsetLeft}}else{q.style.width=c.m.tileSize+"px";j=v.offsetLeft;r=j+v.offsetWidth;if(l.displacement<0){u=c.m.emptyRef.x+1;t=c.m.emptyRef.y;s=v.offsetTop+v.offsetHeight;k=A.offsetTop}else{s=A.offsetTop+A.offsetHeight;
k=v.offsetTop}}c.log("lowx ="+k+" upperx="+s+" lowy="+j+" uppery="+r);for(var x=0;x<y;x++){var C=c.v.createEl("div",{className:"tile "+c.m.state[u][t]+" floatleft"});q.appendChild(C);if(l.direction==="y"){t++}else{u++}}d.previewDrag.appendChild(q);i=h({x:f(m.x),y:f(m.y)},{x:f(c.m.emptyRef.x),y:f(c.m.emptyRef.y)})
}else{if(z=="drag"){c.log("x="+D.lastY+" y="+D.lastX);if(D.lastX>=j&&D.lastX<=r&&D.lastY>=k&&D.lastY<=s){d.isDragged=true;q.style.left=(D.lastX+5)+"px";q.style.top=(D.lastY+5)+"px";q.style.visibility="visible"}else{q.style.visibility="hidden"}}else{if(z=="dragend"){if(!B.droppedOnMySelf){d.isDragged=false
}n=h({x:f(m.x),y:f(m.y)},{x:D.lastY-e,y:D.lastX-g});c.log("actual ="+i+" draggedDistance="+n);if(n>(i/2)&&q.style.visibility=="visible"){c.log("Drag criteria is obeyed");d.isDragged=false;var w=c.c.isMovelLegal(m.x,m.y);(w.isLegal===true)&&c.c.swap({x:m.x,y:m.y},w.direction,w.displacement)}else{d.previewDrag.removeChild(q)
}}else{if(z=="dragcancel"){d.previewDrag.removeChild(q)}}}}},document,m,function(){l=c.c.isMovelLegal(m.x,m.y);return l.isLegal})};this.layoutmanager=function(i){switch(i){case"source":c.v.removeClass(d.sourceHolder,"hide");c.v.addClass(d.placeHolder,"hide");c.v.addClass(d.solutionHolder,"hide");break;
case"game":c.v.removeClass(d.placeHolder,"hide");c.v.addClass(d.sourceHolder,"hide");c.v.addClass(d.solutionHolder,"hide");break;case"solution":c.v.removeClass(d.solutionHolder,"hide");c.v.addClass(d.placeHolder,"hide");c.v.addClass(d.sourceHolder,"hide");break}};var h=function(n,m){var j=m.y,l=m.x,i=n.y,k=n.x;
distance=Math.sqrt(((i-j)*(i-j))+(k-l)*(k-l));c.log("empty x="+j+" empty y="+l);c.log("source x="+i+" source y="+k);return(distance<0?distance*-1:distance)};var f=function(i){return(i*c.m.tileSize)+(c.m.tileSize/2)}};c.v.Box=b})(window,slider);(function(a,c){var b=function(f,k,i,h,g){var e=this;this.callback=k;
this.ele=f;this.doc=i||a.document;this.dragStarted=false;this.mouseIsDown=false;this.dragSourceId=null;this.dropTargetId=null;this.dragData=h;this.dragThreshold=5;var j=function(l){var m;if(l.touches&&l.touches.length){m=l.touches[0].target.id}else{m=(l.target||l.srcElement).id}return m};var d=function(m){var l=[];
if(m.touches&&m.touches.length){l[0]=m.touches[0].clientX;l[1]=m.touches[0].clientY}else{l[0]=m.clientX;l[1]=m.clientY}return l};this.touchHandler=function(l){var m=l.changedTouches;if(m.length>1){return false}switch(l.type){case"touchstart":e.onMouseDown(l);break;case"touchmove":e.onMouseMove(l);break;
case"touchend":e.onMouseUp(l);break;case"touchcancel":e.onMouseUp(l,true);break}};this.onMouseDown=function(n){n=window.event||n;var l=d(n);e.startX=e.lastX=l[0];e.startY=e.lastY=l[1];if(n.type==="touchstart"){c.v.removeHandler(f,"mousedown",e.onMouseDown);c.v.addHandler(f,"touchmove",e.touchHandler);
c.v.addHandler(f,"touchend",e.touchHandler);c.v.addHandler(document.body,"touchcancel",e.touchHandler)}else{var m=n.which||n.button;if(m!=1){return}if(e.mouseIsDown){return}e.mouseIsDown=true;c.v.addHandler(e.doc,"mousemove",e.onMouseMove);c.v.addHandler(e.doc,"mouseup",e.onMouseUp);c.v.addHandler(e.doc,"blur",e.onMouseUp);
c.v.cancelEvent(n);c.v.stopEventPropogation(n)}};this.onMouseUp=function(m,l){e.mouseIsDown=false;m=window.event||m;if(m.type==="touchend"||m.type==="touchcancel"){c.v.removeHandler(f,"touchmove",e.touchHandler);c.v.removeHandler(f,"touchend",e.touchHandler);c.v.removeHandler(document.body,"touchcancel",e.touchHandler)
}else{c.v.removeHandler(e.doc,"mousemove",e.onMouseMove);c.v.removeHandler(e.doc,"mouseup",e.onMouseUp);c.v.removeHandler(e.doc,"blur",e.onMouseUp);c.v.cancelEvent(m);c.v.stopEventPropogation(m)}e.dropTargetId=j(m);if(e.dragStarted){l?e.doCallback("dragcancel"):e.doCallback("dragend",{droppedEleId:e.dropTargetId,droppedOnMySelf:(e.dragSourceId===e.dropTargetId)})
}e.dragStarted=false};this.onMouseMove=function(n){n=window.event||n;var m=d(n);e.lastX=m[0];e.lastY=m[1];if(c.isIE&&n.button==0&&!window.performance){return e.onMouseUp()}if(!e.dragStarted){var l=Math.max(Math.abs(e.startX-e.lastX),Math.abs(e.startY-e.lastY))}if(!e.dragStarted&&l>=e.dragThreshold){e.dragStarted=true;
e.doCallback("dragstart");e.dragSourceId=j(n)}else{if(!e.dragStarted){return c.v.cancelEvent(n)}}if(n.type==="mousemove"){c.v.cancelEvent(n);c.v.stopEventPropogation(n)}e.doCallback("drag")};this.doCallback=function(l,m){if(e.callback&&typeof e.callback=="function"){e.callback.call(e.ele,l,{startX:e.startX,lastX:e.lastX,startY:e.startY,lastY:e.lastY},m)
}};c.v.addHandler(f,"mousedown",function(l){g()&&e.onMouseDown(l)});c.v.addHandler(f,"touchstart",function(l){g()&&e.onMouseDown(l)});c.v.addHandler(document.body,"touchmove",function(l){l.preventDefault()})};c.v.Drag=b})(window,slider);(function(a,b){b.v.addHandler=function(){if(window.addEventListener){return function(e,c,d){e.addEventListener(c,d,false)
}}else{if(window.attachEvent){return function(e,c,d){e.attachEvent("on"+c,d)}}}}();b.v.removeHandler=function(){if(window.removeEventListener){return function(e,c,d){e.removeEventListener(c,d,false)}}else{if(window.attachEvent){return function(e,c,d){e.detachEvent("on"+c,d)}}}}();b.v.createEl=function(d,c){if(typeof d!="string"){return null
}var e=document.createElement(d);if(c){if(c.id){e.id=c.id}if(c.className){e.className=c.className}if(c["class"]){e.className=c["class"]}if(c.title){e.title=c.title}if(c.type){e.type=c.type}if(c.value){e.value=c.value}if(c.cssText){e.cssText=c.cssText}if(c.alt){e.alt=c.alt}if(c.src){e.src=c.src}if(c.html){e.innerHTML=c.html
}if(c.align){e.align=c.align}if(c.text){p.View.text(e,c.text)}if(c.name){e.name=c.name}if(c.tabIndex){e.tabIndex=c.tabIndex}}return e};b.v.stopEventPropogation=function(c){if(c&&c.stopPropagation){c.stopPropagation()}if(c){c.cancelBubble=true}};b.v.cancelEvent=function(c){if(typeof c.preventDefault=="function"){c.preventDefault()
}else{c.returnValue=false}};b.v.getEl=function(c){return document.getElementById(c)};b.v.hasClass=function(d,c){if(!d){return}if(d.classList){return d.classList.contains(c)}return(" "+d.className+" ").indexOf(" "+c+" ")>-1};b.v.addClass=function(d,c){if(!d){return}if(d.classList){return d.classList.add(c)
}if(!b.v.hasClass(d,c)){d.className=b.v.getTrimString(d.className+" "+c)}};b.v.setClass=function(d,c){d.className=c};b.v.removeClass=function(d,c){if(!d){return}if(d.classList){return d.classList.remove(c)}if(b.v.hasClass(d,c)){d.className=b.v.getTrimString(d.className.replace(new RegExp("(^|\\s)"+c+"(\\s|$)")," "))
}};b.v.getTrimString=function(c){if(c){var d=/^\s+|\s+$/g;return c.replace(d,"")}else{return""}};b.v.addHandler(a,"load",function(){b.v.puzzle=new b.v.Box();b.v.puzzle.paintPuzzle();if(!("ontouchstart" in document.documentElement)&&b.isMobile){alert("Your mobile web browser is not HTML5 touch compatible, Dragging feature wouldn't work")
}})})(window,slider);